# Permalinks
permalink:           pretty

# Setup
title:               Auste's Data Science blog
tagline:             The Beginning...
url:                 https://Auste1989.github.io/
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Auste Mastaviciute
  url:               https://www.linkedin.com/in/auste-mastaviciute-59a58a54/
  email:             auste.m@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Auste1989

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
